name: live_score
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  bloc: ^8.1.4
  dio: ^5.5.0+1
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_modular: ^6.3.4
  freezed: ^2.5.2
  intl: ^0.19.0
  logger: ^2.4.0
  retrofit: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.2

flutter:
  uses-material-design: true
  assets:
    - .env
